--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/AIPTU/CraftingPlus
branches:
- master
projects:
  CraftingPlus:
    path: ""
    icon: "icon.png"
    lint:
      phpstan: false
...
